# Generated by Django 2.1 on 2018-08-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('classid', models.CharField(max_length=256)),
                ('money', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='schoold',
            new_name='schoolid',
        ),
    ]
