# Generated by Django 2.1 on 2018-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180803_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='monthreport',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='monthreport_content',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='playcard',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='weekereport',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='weekereport_content',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
