# Generated by Django 2.1 on 2018-08-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180803_0732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buys',
        ),
        migrations.RemoveField(
            model_name='users',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='outtime',
        ),
    ]
